### ISSUE TITLE
Requesting Athena query for Rate based rule analysis with aggregation keys ?

### ISSUE THREAD

**Issue by kbbheemi** [aws-samples/waf-log-sample-athena-queries#1]
RBR with custom agg key IP/URI is a feature that customers use. In general customers can add these in with a limit of 100, while this needs checking and they are highly effective at blocking DDoS-like behavior from clients.

**Comment by jlizen** [comment]
In addition to URI, would be great to include a sample that shows a key pointed to a named header as well. That is one of the trickier queries since you have to unpack the header array.

**Comment by kbbheemi** [comment]
We are uploading new queries this week as requested.

**Comment by kbbheemi** [comment]
We added the following new queries:

https://github.com/aws-samples/waf-log-sample-athena-queries/blob/main/sql/trafficByRBRURI.sql
https://github.com/aws-samples/waf-log-sample-athena-queries/blob/main/sql/trafficByRBRheader.sql
https://github.com/aws-samples/waf-log-sample-athena-queries/blob/main/sql/rbrheaderhthreshold.sql
https://github.com/aws-samples/waf-log-sample-athena-queries/blob/main/sql/rbrclientipurithreshold.sql
https://github.com/aws-samples/waf-log-sample-athena-queries/blob/main/sql/rbrheaderthreshold.sql
